Repository mojimojicorp/MojimojiMemoji, pull requests merged in 2020-05, with the labels that each got.

#15 Feat #13 #14 폴더리스트와 메모리스트 마크업
  package.json
  src/components/FolderList/index.tsx
  src/components/FolderList/styles.scss
  src/components/FolderList/styles.scss.d.ts
  src/components/Header/index.tsx
  src/components/Header/styles.scss
  src/components/Header/styles.scss.d.ts
  src/components/MemoList/index.tsx
  src/components/MemoList/styles.scss
  src/components/MemoList/styles.scss.d.ts
  src/containers/App/index.tsx
  src/containers/App/styles.scss
  src/types/import-png.d.ts
  webpack.config.js
  yarn.lock
Labels: markup🎨

#17 [Feat] #5 로그인 페이지 UI 추가
  src/containers/App/styles.scss
  src/containers/LoginPage/index.tsx
  src/containers/LoginPage/styles.scss
  src/containers/LoginPage/styles.scss.d.ts
Labels: front-end👀, markup🎨

#18 [Refact] #13 FolderList, MemoList container로 변경
  src/components/FolderList/index.tsx
  src/components/MemoList/index.tsx
  src/containers/App/index.tsx
  src/containers/FolderListPage/index.tsx
  src/containers/FolderListPage/styles.scss
  src/containers/FolderListPage/styles.scss.d.ts
  src/containers/MemoListPage/index.tsx
  src/containers/MemoListPage/styles.scss
  src/containers/MemoListPage/styles.scss.d.ts
Labels: markup🎨, refactor🔄

#21 [Refact] 모노리포 관리를 위한 폴더구조 변경
  api-server/.gitkeep
  app/.babelrc
  app/.eslintignore
  app/.eslintrc
  app/.gitignore
  app/.prettierrc
  app/README.md
  app/index.html
  app/manifest.json
  app/package.json
  app/src/components/Header/index.tsx
  app/src/components/Header/styles.scss
  app/src/components/Header/styles.scss.d.ts
  app/src/containers/App/index.tsx
  app/src/containers/App/styles.scss
  app/src/containers/App/styles.scss.d.ts
  app/src/containers/FolderListPage/index.tsx
  app/src/containers/FolderListPage/styles.scss
  app/src/containers/FolderListPage/styles.scss.d.ts
  app/src/containers/LoginPage/index.tsx
  app/src/containers/LoginPage/styles.scss
  app/src/containers/LoginPage/styles.scss.d.ts
  app/src/containers/MemoEditPage/index.tsx
  app/src/containers/MemoEditPage/styles.scss
  app/src/containers/MemoEditPage/styles.scss.d.ts
  app/src/containers/MemoListPage/index.tsx
  app/src/containers/MemoListPage/styles.scss
  app/src/containers/MemoListPage/styles.scss.d.ts
  app/src/images/body/add_btn.png
  app/src/images/body/background.png
  app/src/images/body/folder_btn.png
  app/src/images/body/logo_618x618.png
  app/src/images/body/more_btn.png
  app/src/images/body/naverLogin_btn.png
  app/src/images/header/back_btn.png
  app/src/images/header/logout_btn.png
  app/src/images/icon_64x64.png
  app/src/images/icons.png
  app/src/index.tsx
  app/src/types/declarations.d.ts
  app/src/types/import-png.d.ts
  app/src/utils/.keep
  app/tsconfig.json
  app/webpack.config.js
  app/yarn.lock
Labels: refactor🔄

#26 [Docs] #25 README.md 파일 경로 이동
  README.md
Labels: documentation📃

#20 [Feat] #16 router 나누기
  app/package.json
  app/src/containers/App/index.tsx
  app/src/index.tsx
  app/webpack.config.js
  app/yarn.lock
Labels: front-end👀

#28 Feat #14 memo list page 메모추가 버튼 추가, memo edit page 아이콘 수정
  app/manifest.json
  app/src/components/Header/index.tsx
  app/src/components/Header/styles.scss
  app/src/components/Header/styles.scss.d.ts
  app/src/containers/App/styles.scss
  app/src/containers/App/styles.scss.d.ts
  app/src/containers/FolderListPage/index.tsx
  app/src/containers/FolderListPage/styles.scss
  app/src/containers/FolderListPage/styles.scss.d.ts
  app/src/containers/LoginPage/index.tsx
  app/src/containers/LoginPage/styles.scss
  app/src/containers/LoginPage/styles.scss.d.ts
  app/src/containers/MemoEditPage/index.tsx
  app/src/containers/MemoEditPage/styles.scss
  app/src/containers/MemoEditPage/styles.scss.d.ts
  app/src/containers/MemoListPage/index.tsx
  app/src/containers/MemoListPage/styles.scss
  app/src/containers/MemoListPage/styles.scss.d.ts
  app/src/images/icons.png
  app/src/index.tsx
  app/src/types/declarations.d.ts
  app/src/types/import-png.d.ts
  app/yarn.lock
Labels: front-end👀, markup🎨

#39 [feat] #36 header button을 url에 따라 조정
  README.md
  app/src/components/Folder/index.tsx
  app/src/components/Folder/styles.scss
  app/src/components/Folder/styles.scss.d.ts
  app/src/components/FolderSetting/styles.scss.d.ts
  app/src/components/Header/index.tsx
  app/src/components/Header/styles.scss
  app/src/components/Header/styles.scss.d.ts
  app/src/components/MemoSetting/styles.scss.d.ts
  app/src/containers/App/index.tsx
  app/src/containers/FolderListPage/index.tsx
  app/src/containers/FolderListPage/styles.scss.d.ts
  app/src/containers/MemoEditPage/index.tsx
  app/src/containers/MemoListPage/index.tsx
  app/src/containers/MemoListPage/styles.scss.d.ts
Labels: feature👩‍🔧, front-end👀

#41 [Feat] #37 반응형웹을 위한 뷰포트설정
  app/index.html
  git-commit-template.txt
Labels: setting🔨
