Repository mojimojicorp/MojimojiMemoji, pull requests merged in 2020-06, with the labels that each got.

#43 [Feat] #37 memo editor text 효과 기능
  app/src/containers/MemoEditPage/index.tsx
  app/src/containers/MemoEditPage/styles.scss
  app/src/containers/MemoEditPage/styles.scss.d.ts
  app/src/images/icons.png
Labels: feature👩‍🔧, front-end👀

#44 [Feat/#32] 폴더리스트 페이지 기능 구현
  app/.eslintrc
  app/.prettierrc
  app/src/components/Folder/colors.ts
  app/src/components/Folder/index.tsx
  app/src/components/Folder/styles.scss
  app/src/components/FolderSetting/index.tsx
  app/src/components/FolderSetting/styles.scss
  app/src/components/FolderSetting/styles.scss.d.ts
  app/src/components/Header/index.tsx
  app/src/containers/FolderListPage/index.tsx
  app/src/containers/FolderListPage/styles.scss
  app/src/containers/FolderListPage/styles.scss.d.ts
  app/src/containers/MemoEditPage/index.tsx
  app/src/containers/MemoListPage/index.tsx
  app/src/mock/folders.ts
  app/src/types/ObjectType.ts
  app/src/types/declarations.d.ts
  app/src/types/folderType.ts
Labels: front-end👀

#46 Update ObjectType.ts
  app/src/types/ObjectType.ts
Labels: refactor🔄
